# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyze_exam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_analyze_exam(object):
    def setupUi(self, analyze_exam):
        analyze_exam.setObjectName("analyze_exam")
        analyze_exam.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(analyze_exam)
        self.centralwidget.setObjectName("centralwidget")
        self.exam_list_analyze_exam = QtWidgets.QListWidget(self.centralwidget)
        self.exam_list_analyze_exam.setGeometry(QtCore.QRect(30, 110, 721, 401))
        self.exam_list_analyze_exam.setObjectName("exam_list_analyze_exam")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 60, 371, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(660, 530, 91, 31))
        self.pushButton.setObjectName("pushButton")
        analyze_exam.setCentralWidget(self.centralwidget)

        self.retranslateUi(analyze_exam)
        self.pushButton.clicked.connect(analyze_exam.analyzeExam)
        QtCore.QMetaObject.connectSlotsByName(analyze_exam)

    def retranslateUi(self, analyze_exam):
        _translate = QtCore.QCoreApplication.translate
        analyze_exam.setWindowTitle(_translate("analyze_exam", "채점"))
        self.label.setText(_translate("analyze_exam", "채점할 모의고사를 선택하세요"))
        self.pushButton.setText(_translate("analyze_exam", "채점하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    analyze_exam = QtWidgets.QMainWindow()
    ui = Ui_analyze_exam()
    ui.setupUi(analyze_exam)
    analyze_exam.show()
    sys.exit(app.exec_())
