# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_exam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_exam(object):
    def setupUi(self, show_exam):
        show_exam.setObjectName("show_exam")
        show_exam.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(show_exam)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 371, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.exam_list_show_exam = QtWidgets.QListWidget(self.centralwidget)
        self.exam_list_show_exam.setGeometry(QtCore.QRect(40, 80, 721, 401))
        self.exam_list_show_exam.setObjectName("exam_list_show_exam")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 500, 91, 31))
        self.pushButton.setObjectName("pushButton")
        show_exam.setCentralWidget(self.centralwidget)

        self.retranslateUi(show_exam)
        self.pushButton.clicked.connect(show_exam.openShowExam2)
        QtCore.QMetaObject.connectSlotsByName(show_exam)

    def retranslateUi(self, show_exam):
        _translate = QtCore.QCoreApplication.translate
        show_exam.setWindowTitle(_translate("show_exam", "채점 및 분석 결과 열람"))
        self.label.setText(_translate("show_exam", "열람할 모의고사를 선택하세요"))
        self.pushButton.setText(_translate("show_exam", "열람하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    show_exam = QtWidgets.QMainWindow()
    ui = Ui_show_exam()
    ui.setupUi(show_exam)
    show_exam.show()
    sys.exit(app.exec_())
