# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_exam_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_exam_2(object):
    def setupUi(self, show_exam_2):
        show_exam_2.setObjectName("show_exam_2")
        show_exam_2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(show_exam_2)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 70, 711, 391))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 371, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 500, 641, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        show_exam_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(show_exam_2)
        self.pushButton_3.clicked.connect(show_exam_2.showAnalyzedExam)
        self.pushButton_2.clicked.connect(show_exam_2.showAnalyzedStudents)
        self.pushButton_1.clicked.connect(show_exam_2.showAnalyzedBranches)
        QtCore.QMetaObject.connectSlotsByName(show_exam_2)

    def retranslateUi(self, show_exam_2):
        _translate = QtCore.QCoreApplication.translate
        show_exam_2.setWindowTitle(_translate("show_exam_2", "채점 및 분석 결과 열람"))
        self.label.setText(_translate("show_exam_2", "기본 정보"))
        self.pushButton_3.setText(_translate("show_exam_2", "모의고사 문항분석"))
        self.pushButton_2.setText(_translate("show_exam_2", "학생 전체 점수 열람"))
        self.pushButton_1.setText(_translate("show_exam_2", "학생별 성적표 열람"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    show_exam_2 = QtWidgets.QMainWindow()
    ui = Ui_show_exam_2()
    ui.setupUi(show_exam_2)
    show_exam_2.show()
    sys.exit(app.exec_())
